name: Node.js CI

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: 'Configurando SSH'
              run: |
                echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
                
                chmod 400 key.pem
                
            - name: 'Conectar a EC2 y Actualizando repositorio'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-52-23-227-177.compute-1.amazonaws.com "rm -rf  /var/www/html"
            - name: 'Clonar repositorio en EC2'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-52-23-227-177.compute-1.amazonaws.com "git clone https://github.com/KennethTaipe06/html.git /var/www/html"
            - name: 'Reiniciar Servicio'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-52-23-227-177.compute-1.amazonaws.com "systemctl restart nginx"
            - name: 'Eliminar clave SSH'
              run: rm key.pem


            - name: 'Configurando SSH2'
              run: |
                echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
                
                chmod 400 key.pem
                
            - name: 'Conectar a EC2 y Actualizando repositorio'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-54-90-71-58.compute-1.amazonaws.com "rm -rf  /var/www/html"
            - name: 'Clonar repositorio en EC2'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-54-90-71-58.compute-1.amazonaws.com "git clone https://github.com/KennethTaipe06/html.git /var/www/html"
            - name: 'Reiniciar Servicio'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-54-90-71-58.compute-1.amazonaws.com "systemctl restart nginx"
            - name: 'Eliminar clave SSH'
              run: rm key.pem