name: Node.js CI

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: 'Configurar clave SSH'
              run: |
                echo "-----BEGIN RSA PRIVATE KEY-----
                MIIEogIBAAKCAQEAxn34DDO9+/h3QCrZw/R1wavr4USPuo1hzbs6S4PuR01WS7LP
                GuJfqnqZ1kAgcvCYnK8DMbs2c9Xv5wilpf04OjEyr2DMHvty5IZsbE77aD4MDhbs
                n7fsR2GGNNQKfG6s6SE10KMxmBWAIuUor6iChf7ryG+6ax6YMNZUfIz4zyOr+P+D
                fAn9mgH51zhLiKcyxXWinH9VtmPpq027UaonlTSDRy/9Jp5dkuCutt/qwr64669/
                6wAbxVftSSLLGmwlOsgPmdTWMFTobdBL7jYbSNpn+UBiqGfABYRpVft9YNEItb/B
                ils459EeBwvWPb0WDJH2dkUFZBM4VOfLic1hYwIDAQABAoIBACMhQlhug+5ngDuU
                GeyLhJfdZKb+6m06/pdZzqx00iQ+dMp7ABqi/AmBH18DBHszR99bPjZ8CtwffhEm
                v6KMGXp7IJxXhmjpWeFGRUQ6ClbdvGZ1+jUeaSwM/6Kz8JMrR2EPZqXhbDKdg4sp
                gbTtHwS2JGbaF2VECe2C0XslvBd0ybnFwc+NCuUQOHB51kQ0SeWHd1oUwUiIpAU2
                Rc0bCANBfgWz2pJLoSmeCElP/omMEybb78rwE7unQQIxK5g0vMXIR18UtYpxn/ur
                opcWhdTEoxSg03+/N91GYN7rJ4h0cSFAA8JZUtFQYnpDIhSdvOqElqPtqItlcz2H
                euLZwRkCgYEA9H1O3j8/mPjPvlbbSA7QnNm0uY6Q9Kt24h8mx2E25m4EEAd+0eJ2
                ARr+D3AWXyiuwaQqxQthAYEG06bsJhU7TBcghJu+Nq5AUcr7Ecvndu1SdVH/HFLI
                N8JqLGmClKrzxzgkSlfi1s4HH/4uaNqMtXOAuPMhlbLTIukzn81U1C0CgYEAz9ZH
                wHdTZjHCA1Z3e3PHT3Pg8BU7+OJF5Yode/QjxlKGee6VmLC4RnVMdEC2K6AvPztb
                AGvtyuJHPe4tbHdmdXSs7MIvro6c7s17dYhnj9NBUw2T3HKnESgmCu043xicIkRl
                euWjxVbgcWgnSnoUmbYwk9HswZ5E/c4rCQ46tc8CgYBo1CGw4WWfbW+FqTA0YUXJ
                Ov9mYF5+ydYbdkfmTSSBAML1LIGP9I2sQ6qTa/frrUHg/UbpXcumHXCT54pxecEH
                CxOCSFTylRw29dVY+BiywWcNrq63sjbu0Yk8qbC3leUYklXdGnnEqGodqZq0kqCq
                XG/g3T6VNSuaWGsuJZgtsQKBgHaKLeRtaojYCmMi9wTXdS8w1XO5eLosPFd+HfDr
                v1fHC+IRnQs4h/HPxyprGjvpoej7rpyf8kGMK7v707aQp0SIpnRnERELUCC33Bme
                EgsrH5ACJ3pNflI/xurmgFBmVe8JeaPNxEmyklK8Z+SHmqZNDonQ6qtH3OuxokQI
                9J1rAoGAHQJUnKeDzfaGFPUBKIVqv55OR18xfxvHUf9Lq5E6Nay4JHI36BNoTbZo
                3Npzv5u0n0DkvMeENl+hzuCcte5fCCK4bOYpkUlRTnGuoHmf4aeHi7z1YorX1A79
                XQH4a018NH0AORlXEx75LvKuwZmutX4tP0gxLLPcZ9gxmtSxoBE=
                -----END RSA PRIVATE KEY-----" > key.pem
                chmod 400 key.pem
            - name: 'Conectar a EC2 y borrar carpeta'
              run: |
                ssh -i "key.pem" ec2-user@ec2-3-84-26-23.compute-1.amazonaws.com "rm -rf /downloads/Node-Proyect"
            - name: 'Clonar repositorio en EC2'
              run: |
                ssh -i "key.pem" ec2-user@ec2-3-84-26-23.compute-1.amazonaws.com "git clone https://github.com/KennethTaipe06/Node-Proyect.git /downloads/Node-Proyect"
            - name: 'Eliminar clave SSH'
              run: rm key.pem