name: Node.js CI

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: 'Mostrar mensaje'
              run: echo 'Hola, mundo!'
